{
 "title": "Adapter-Service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\"adapter-service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Consumer Lag (per instance & topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (member_host, topic) (kafka_consumergroup_group_lag{group=~\"adapter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag (topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_group_topic_sum_lag{group=~\"adapter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}