{
 "title": "ExplorViz Services",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\".*-service\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percentage of CPU usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(job) (process_cpu_usage)",
     "legendFormat": "{{job}}"
    },
    { "expr": "sum(process_cpu_usage)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    },
    { "expr": "sum (jvm_memory_used_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Record Consumption Rate",
   "type": "timeseries",
   "description": "Average number of records consumed per second (per service and topic)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, topic) (kafka_consumer_fetch_manager_records_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"})",
     "legendFormat": "{{job}} ({{topic}})"
    },
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"}",
     "legendFormat": "{{job}}:{{instance}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Byte Consumption Rate",
   "type": "timeseries",
   "description": "Average bytes consumed per second (per service and topic)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(job, topic) (kafka_consumer_fetch_manager_bytes_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"})",
     "legendFormat": "{{job}} ({{topic}})"
    },
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{topic!~\".*KSTREAM.*\", topic!~\".*KTABLE.*\", topic!=\"token-events\", topic=~\".+\"}",
     "legendFormat": "{{job}}:{{instance}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "description": "Current and average difference between the latest offset and the consumer offset, summed over all partitions.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (kafka_consumer_fetch_manager_records_lag{topic!~\".*TABLE.*\", topic!~\".*STATE-STORE.*\", topic!=\"token-events\"})",
     "legendFormat": "{{job}} current"
    },
    {
     "expr": "sum by(job) (kafka_consumer_fetch_manager_records_lag_avg{topic!~\".*TABLE.*\", topic!~\".*STATE-STORE.*\", topic!=\"token-events\"})",
     "legendFormat": "{{job}} average"
    }
   ]
  },
  {
   "title": "Processing Latency per Instance",
   "type": "timeseries",
   "description": "The average execution time in ms across all running tasks of this thread.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_stream_thread_process_latency_avg",
     "legendFormat": "{{job}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Token Events",
   "type": "stat",
   "description": "Token Event sent by the user service and received by the others.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (round(increase(kafka_consumer_fetch_manager_records_consumed_total{topic=\"token-events\"}[$__range])))",
     "legendFormat": "{{job}} received"
    },
    {
     "expr": "sum by(job) (round(increase(kafka_producer_topic_record_send_total{topic=\"token-events\"}[$__range])))",
     "legendFormat": "{{job}} sent"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "Inbound requests per service. Includes scraping by prometheus.",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(job) ((increase(http_server_requests_seconds_count{uri!~\"/q.*|/metrics/\", outcome != \"REDIRECTION\"}[$__range]))))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average HTTP Response TIme (Success)",
   "type": "timeseries",
   "description": "Average time it took the server to respond to a request to a certain url. Only shows successful requests.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{uri!~\"/q.*|/metrics/\", job=~\"landscape-service|trace-service\", outcome = \"SUCCESS\"}[5m]) ",
     "legendFormat": "{{uri}} ({{job}})"
    }
   ]
  },
  {
   "title": "HTTP Outcomes",
   "type": "stat",
   "description": "Inbound requests per service. Includes scraping by prometheus.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job, outcome)\n (round(increase(http_server_requests_seconds_count{uri!~\"/q.*|/metrics/\", outcome != \"REDIRECTION\"}[$__range])))",
     "legendFormat": "{{job}} {{outcome}}"
    }
   ]
  }
 ]
}