{
 "title": "Landscape-Service",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "time_duration", "query": "30s:15s" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Instance Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\"landscape-service\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Spans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total # of Received Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance) (explorviz_total_received_spans_total >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iRate of Received Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance) (irate((explorviz_total_received_spans_total >= 0)[$time_duration]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total # of Cached Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (instance) (explorviz_total_cached_spans_total >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (instance) (rate((explorviz_total_received_spans_total >= 0)[$time_duration]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total # of Discarded Spans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (instance) (explorviz_total_discarded_spans_total >= 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Consumer Lag (per instance & topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (member_host, topic) (kafka_consumergroup_group_lag{group=~\"landscape.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag (topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_consumergroup_group_topic_sum_lag{group=~\"landscape.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } }
 ]
}