include: "/.gitlab-ci-explorviz-common.yml"

stages:
  - test


run-pre-commit:
  stage: test
  image: explorviz/pre-commit:latest
  script:
    - pre-commit run --all-files --config .pre-commit-config.yaml
