services:
  ## Backend Mock ##

  backend-mock:
    container_name: explorviz-backend-mock
    image: explorviz/backend-mock:latest
    networks:
      - explorviz
    ports:
      - 8083:8083
      - 8084:8084

networks:
  explorviz:
    name: explorviz
