{
 "title": "ExplorViz Services",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\".*-service\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percentage of CPU usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" },
    { "expr": "sum(process_cpu_usage)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    },
    { "expr": "sum (jvm_memory_used_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Record Consumption Rate",
   "type": "graph",
   "description": "Average number of records consumed per second (per service and topic)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{topic!~\".*KSTREAM.*\", topic!=\"token-events\", topic=~\".+\"}",
     "legendFormat": "{{job}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Byte Consumption Rate",
   "type": "graph",
   "description": "Average number of bytes consumed per second (per service and topic)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{topic!~\".*KSTREAM.*\", topic!=\"token-events\", topic=~\".+\"}",
     "legendFormat": "{{job}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "Inbound requests per service. Includes scraping by prometheus.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by(job) ((increase(http_server_requests_seconds_count{uri!~\"/q.*|/metrics/\", outcome != \"REDIRECTION\"}[$__range]))))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average HTTP Response TIme (Success)",
   "type": "timeseries",
   "description": "Average time it took the server to respond to a request to a certain url. Only shows successful requests.",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{uri!~\"/q.*|/metrics/\", job=~\"landscape-service|trace-service\", outcome = \"SUCCESS\"}[5m]) ",
     "legendFormat": "{{uri}} ({{job}})"
    }
   ]
  },
  {
   "title": "HTTP Outcomes",
   "type": "stat",
   "description": "Inbound requests per service. Includes scraping by prometheus.",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job, outcome)\n (round(increase(http_server_requests_seconds_count{uri!~\"/q.*|/metrics/\", outcome != \"REDIRECTION\"}[$__range])))",
     "legendFormat": "{{job}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Share between topics in %",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": " kafka_consumer_fetch_manager_bytes_consumed_rate\n/ ignoring(job) group_left\n  sum without(job)(kafka_consumer_fetch_manager_bytes_consumed_rate)"
    }
   ]
  }
 ]
}