{
 "title": "ExplorViz Services",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Service Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (up{job=~\".*-service\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Percentage of CPU usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage per service",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes)",
     "legendFormat": "{{job}}"
    },
    { "expr": "sum (jvm_memory_used_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Record Consumption Rate",
   "type": "graph",
   "description": "Average number of records consumed per second (per service and topic)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{topic!~\".*KSTREAM.*\", topic!=\"token-events\"}",
     "legendFormat": "{{job}} ({{topic}})"
    }
   ]
  }
 ]
}